-- DeptFlow baseline schema (PostgreSQL). Generated from META-INF/orm.xml.

create table departments (is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, head_person_id uuid, id uuid not null, institution_id uuid not null, parent_department_id uuid, code varchar(255) not null, name varchar(255) not null, primary key (id), unique (institution_id, code));
create table document_types (is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, id uuid not null, institution_id uuid not null, description varchar(255), name varchar(255) not null, primary key (id));
create table document_versions (version_number integer not null, created_at timestamp(6) with time zone not null, reviewed_at timestamp(6) with time zone, size_bytes bigint not null, submitted_at timestamp(6) with time zone, created_by_person_id uuid, document_id uuid not null, id uuid not null, reviewed_by_person_id uuid, submitted_by_person_id uuid, change_note varchar(255), content_type varchar(255) not null, file_name varchar(255) not null, review_comment varchar(255), status varchar(255) not null check ((status in ('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED'))), storage_key varchar(255) not null, storage_provider varchar(255), primary key (id), unique (document_id, version_number));
create table documents (created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, created_by_person_id uuid, department_id uuid not null, document_type_id uuid, id uuid not null, institution_id uuid not null, description varchar(255), status varchar(255) not null check ((status in ('DRAFT','PENDING_APPROVAL','PUBLISHED','ARCHIVED'))), title varchar(255) not null, primary key (id));
create table institutions (is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, id uuid not null, parent_institution_id uuid, code varchar(255) not null, name varchar(255) not null, primary key (id), unique (code));
create table person_departments (end_date date, is_primary boolean not null, start_date date not null, department_id uuid not null, id uuid not null, person_id uuid not null, role_id uuid not null, primary key (id), unique (person_id, department_id, start_date));
create table persons (is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, id uuid not null, institution_id uuid not null, user_id uuid, email varchar(255), first_name varchar(255) not null, job_title varchar(255), last_name varchar(255) not null, phone varchar(255), primary key (id));
create table roles (can_approve_documents boolean not null, is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, id uuid not null, institution_id uuid not null, description varchar(255), name varchar(255) not null, primary key (id), unique (institution_id, name));
create table user_accounts (is_active boolean not null, created_at timestamp(6) with time zone not null, updated_at timestamp(6) with time zone not null, id uuid not null, email varchar(255) not null, password_hash varchar(255) not null, username varchar(255) not null, primary key (id), unique (username), unique (email));
alter table if exists document_versions add constraint FKi6p7dgv96b8s8ivf84hqo9pt foreign key (document_id) references documents;
