-- DeptFlow baseline schema (SQL Server). Generated from META-INF/orm.xml.

create table departments (is_active bit not null, created_at datetimeoffset(7) not null, updated_at datetimeoffset(7) not null, head_person_id uniqueidentifier, id uniqueidentifier not null, institution_id uniqueidentifier not null, parent_department_id uniqueidentifier, code varchar(255) not null, name varchar(255) not null, primary key (id));
create table document_types (is_active bit not null, created_at datetimeoffset(7) not null, updated_at datetimeoffset(7) not null, id uniqueidentifier not null, institution_id uniqueidentifier not null, description varchar(255), name varchar(255) not null, primary key (id));
create table document_versions (version_number int not null, created_at datetimeoffset(7) not null, reviewed_at datetimeoffset(7), size_bytes bigint not null, submitted_at datetimeoffset(7), created_by_person_id uniqueidentifier, document_id uniqueidentifier not null, id uniqueidentifier not null, reviewed_by_person_id uniqueidentifier, submitted_by_person_id uniqueidentifier, change_note varchar(255), content_type varchar(255) not null, file_name varchar(255) not null, review_comment varchar(255), status varchar(255) not null check ((status in ('DRAFT','PENDING_APPROVAL','APPROVED','REJECTED'))), storage_key varchar(255) not null, storage_provider varchar(255), primary key (id));
create table documents (created_at datetimeoffset(7) not null, updated_at datetimeoffset(7) not null, created_by_person_id uniqueidentifier, department_id uniqueidentifier not null, document_type_id uniqueidentifier, id uniqueidentifier not null, institution_id uniqueidentifier not null, description varchar(255), status varchar(255) not null check ((status in ('DRAFT','PENDING_APPROVAL','PUBLISHED','ARCHIVED'))), title varchar(255) not null, primary key (id));
create table institutions (is_active bit not null, created_at datetimeoffset(7) not null, updated_at datetimeoffset(7) not null, id uniqueidentifier not null, parent_institution_id uniqueidentifier, code varchar(255) not null, name varchar(255) not null, primary key (id));
create table person_departments (end_date date, is_primary bit not null, start_date date not null, department_id uniqueidentifier not null, id uniqueidentifier not null, person_id uniqueidentifier not null, role_id uniqueidentifier not null, primary key (id));
create table persons (is_active bit not null, created_at datetimeoffset(7) not null, updated_at datetimeoffset(7) not null, id uniqueidentifier not null, institution_id uniqueidentifier not null, user_id uniqueidentifier, email varchar(255), first_name varchar(255) not null, job_title varchar(255), last_name varchar(255) not null, phone varchar(255), primary key (id));
create table roles (can_approve_documents bit not null, is_active bit not null, created_at datetimeoffset(7) not null, updated_at datetimeoffset(7) not null, id uniqueidentifier not null, institution_id uniqueidentifier not null, description varchar(255), name varchar(255) not null, primary key (id));
create table user_accounts (is_active bit not null, created_at datetimeoffset(7) not null, updated_at datetimeoffset(7) not null, id uniqueidentifier not null, email varchar(255) not null, password_hash varchar(255) not null, username varchar(255) not null, primary key (id));
alter table departments add constraint UKhg9iaojnr03129fub8n1s0utl unique (institution_id, code);
alter table document_versions add constraint UKei968s1e4986g2skkutsuo910 unique (document_id, version_number);
alter table institutions add constraint UK90wcwrx6ap068pspum25xhtyu unique (code);
alter table person_departments add constraint UK6795dqg6i6rru1dagum8gn61y unique (person_id, department_id, start_date);
alter table roles add constraint UK6tencltv56hj7bmbafqga8ql6 unique (institution_id, name);
alter table user_accounts add constraint UKlxwlgwuy2yrbye2vgs9w9x7mr unique (username);
alter table user_accounts add constraint UKf9sl209luxhu4rylls0h1m625 unique (email);
alter table document_versions add constraint FKi6p7dgv96b8s8ivf84hqo9pt foreign key (document_id) references documents;
