spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=deptflow;encrypt=false
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: YourStrong!Passw0rd
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
  flyway:
    enabled: true
    locations: classpath:db/migration/sqlserver
